
version: '2'
services:
  web:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - "REACT_APP_API_URL=http://localhost:3000"
    volumes:
      - .:/app
      - /app/node_modules
    